### ISSUE TITLE
Unexpect behavior from honesty example notebook

### ISSUE THREAD

**Issue by zxchen98** [andyzoujm/representation-engineering#25]
Hi team,

Thank you for your great project! I am recently running your honesty example notebook and trying to run through your provided example. However in the last two cells of honesty.ipynb. I got no meaningful output from the control side. I made no adjustments to the code and used the 7B model. Any ideas would be helpful!

Thanks

![ours_control](https://github.com/andyzoujm/representation-engineering/assets/43800081/5deb7296-3ac2-4b6e-a576-280421a3157b)

**Comment by justinphan3110cais** [comment]
Hi, it's probably because of the variables:
```
layer_id = list(range(-10, -32, -1))
coeff=8.0
```
which needs to be tuned for each model. You can ref to [honesty_mistral.ipynb](https://github.com/andyzoujm/representation-engineering/blob/main/examples/honesty/honesty_mistral.ipynb) for smaller version of honesty-controlled examples with Mistral-7B model.

**Comment by zxchen98** [comment]
Thanks! it works in honesty_mistral.ipynb. But how do you decide which layer_ids to use？

**Comment by zxchen98** [comment]
NVM I found one previous post that answer this question
